### ISSUE TITLE
Bad marshal data

### ISSUE THREAD

**Issue by mohamadder** [ziziwho/clickbot#2]
ValueError: bad marshal data (unknown type code)

Why happen this???
How i solve this easly???

Help me in my below gmail that i register in this site:

mohamadder@gmail.com

Waiting your help

Thanks

**Comment by ziziwho** [comment]
Hi.. I am aware of this issue and it already fixed. Download [clickbot v4](https://github.com/ziziwho/clickbot/releases/tag/v4)
